### PR TITLE
added JIT GIFs

### PR DESCRIPTION
**Pull request by Shivam-AfA**
Signed-off-by: Shivam Sood <shivamsood634@gmail.com>

**Description**

This PR adds The JIT walkthrough GIFs to the src folder.

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
I did a little bit of restructure to make room for future tips and assets. I did some file renaming as all filenames should be lowercased and hyphenated for ease of HTTP-based reference.

**Review by theBeginner86 — COMMENTED** [review]
All walkthroughs look good. 
@Shivam-AfA, one question though.
Why are we clipping the part that shows the MeshMap logo on the top bar in the UI?

**Comment by Shivam-AfA** [comment]
@theBeginner86 It allows us to focus more on the idea of the GIF. Including the top bar makes the main content appear smaller. So I decided to omit it out. Maybe we can try with it also. I'll try to throw in a sample with the top bar.

**Comment by theBeginner86** [comment]
> @theBeginner86 It allows us to focus more on the idea of the GIF. Including the top bar makes the main content appear smaller. So I decided to omit it out. Maybe we can try with it also. I'll try to throw in a sample with the top bar.

Makes sense 👍
I was just wondering if it's _really_ necessary, considering the majority of the demos showcase the name/logo of the project/software so that it's recognizable. 🤔 // @leecalcote

**Comment by Shivam-AfA** [comment]
GIF with meshmap logo.
full

GIF without meshmap logo.
Load design_2


Now as I see, maybe we can include the top bar.

@theBeginner86 @leecalcote

**Comment by leecalcote** [comment]
It's justifiable to exclude the logo, if the view is tightly zoomed on a subset of the UI. In the examples above, that isn't the case. Inclusion of the project name and icon aids in providing users with a consistent frame of reference. In other words, unless the animation is zoomed in, let's display the project's "chrome" to to speak.

**Comment by leecalcote** [comment]
I'm merging what we have now, just to grease the wheels. I recognize that we will change any / all of these gifs.

**Pull request merged**
