### PR TITLE
Replaced recognition banner

### PR DESCRIPTION
**Pull request by ritiksaxena124**
**Description**
The previous banner was not clear and didn't pass the quality check so this PR replaces the old banner with a new banner

**[Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
I wonder if there is a middle ground, because the new image is 2.5MB (large).

**Review by gopivaibhav — COMMENTED** [review]
Just tag me here or on Slack DM after you decrease the size of this banner.

**Review by leecalcote — APPROVED** [review]
lgtm

**Review by gopivaibhav — APPROVED** [review]
LGTM, Thanks!!

**Pull request merged**
