### PR TITLE
added design pioneer badge

### LINKED ISSUE #288: Design Pioneer badge
#### Current Behavior

Add Design pioneer badge under the achievements badge section

#### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by hargunkaur286**
**Description**

This PR fixes #288 

**Notes for Reviewers**
@vishalvivekm please review this

**[Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — CHANGES_REQUESTED** [review]
@vishalvivekm this is a duplicate, no?

**Comment by hargunkaur286** [comment]
@leecalcote Yes, there are two assets folder for all the badges, although one is being used. Not quite sure, why

**Comment by leecalcote** [comment]
> @leecalcote Yes, there are two assets folder for all the badges, although one is being used. Not quite sure, why

Did @vishalvivekm make this request of you? If so, did he explain why?

**Comment by leecalcote** [comment]
@vishalvivekm, please figure this out.

**Comment by vishalvivekm** [comment]
The badges reside in two directories in the repo: 
- `assets/badges/` - for email templates and  Layer5 Cloud 

- `site/static/assets/badges/` for the site : https://badges.layer5.io

> Did @vishalvivekm make this request of you? If so, did he explain why?

The ask here was to add the missing `first-design` ( Design Pioneer) badge to Achievement Badges in https://badges.layer5.io

**Review by vishalvivekm — APPROVED** [review]

**Comment by vishalvivekm** [comment]
invoking the deploy now...

**Comment by vishalvivekm** [comment]
There it is: 
image

Thank you @hargunkaur286. 
We also don't want to make direct changes to the PNGs/SVGs used in the email/cloud, as they may need to be resized according to the templates. **Changes here won't affect those SVGs/PNG.** // @leecalcote

**Pull request merged**
