### PR TITLE
Added continious contributor badge

### PR DESCRIPTION
**Pull request by Rajdip019**
**Description**
Added the Continuous Contributors badge.

**Notes for Reviewers**
Let me know if there are any more places I need to add or link the added files.

**[Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Comment by ritiksaxena124** [comment]
Hey @Rajdip019 could you please remove the space after the hyphen in the name of the badge file in SVG format?

**Comment by ritiksaxena124** [comment]
Final update then we are good to go @Rajdip019, could you please update the SVG and PNG with the files in the [continuous-contribution.zip](https://github.com/layer5labs/meshery-extensions-packages/files/12730131/continuous-contribution.zip) file,

**Comment by Rajdip019** [comment]
[continuous-contribution.zip](https://github.com/layer5labs/meshery-extensions-packages/files/12730347/continuous-contribution.zip)

Here is the file with updated badges. @ritiksaxena124 

I have also changed the readme and added the name of the new badge as well.

**Comment by ritiksaxena124** [comment]
> [continuous-contribution.zip](https://github.com/layer5labs/meshery-extensions-packages/files/12730347/continuous-contribution.zip)
> 
> Here is the file with updated badges. @ritiksaxena124
> 
> I have also changed the readme and added the name of the new badge as well.

Replace the SVG and PNG of the badge that you are using with the SVG and PNG files that are in the zip file that I provided. btw thanks for adding the badge name in Readme

**Comment by Rajdip019** [comment]
@ritiksaxena124 I got it totally wrong haha. I have changed the files now.

**Comment by ritiksaxena124** [comment]
Thank you, LGTM 👏

Looks like you didn't sign your commit

**Review by ritiksaxena124 — APPROVED** [review]

**Comment by Rajdip019** [comment]
> Thank you, LGTM 👏
> 
> Looks like you didn't sign your commit

Fixed

**Pull request merged**
