### PR TITLE
Leaderboard build fix

### PR DESCRIPTION
**Pull request by Kingscliq**
**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by horizenight** [comment]
Hello @Kingscliq 
Kindly Read through the contribution guidelines again. 

1. No mention of which issue is targeted with this pr. 
> **Description**
> 
> This PR fixes #
> 
> **Notes for Reviewers**
> 
> **[Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
> 
> * [x]  Yes, I signed my commits.

2. `DCO check` failed means not all commits were signed consider [rebasing]( https://docs.github.com/en/get-started/using-git/about-git-rebase) your commits and properly signing it.

**Comment by Kingscliq** [comment]
> Hello @Kingscliq Kindly Read through the contribution guidelines again.
> 
> 1. No mention of which issue is targeted with this pr.
> 
> > **Description**
> > This PR fixes #
> > **Notes for Reviewers**
> > **[Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
> > 
> > * [x]   Yes, I signed my commits.
> 
> 2. `DCO check` failed means not all commits were signed consider [rebasing](https://docs.github.com/en/get-started/using-git/about-git-rebase) your commits and properly signing it.

Hi @horizenight, it  was supposed to be a new feature not like a fix, how can I capture that for the context you were speaking from?

**Comment by horizenight** [comment]
Let's tackle one problem at a time : 
1. Your `Pull Request` fails to mention what feature or fix, it is supposed to solve Issue #193  was targeted. This is mentioned in contribution guidelines that` PullRequest` should mention the issue it was solving. 

2. This check is failing as you are not correctly signing your commits, 
so to solve that you would have to [rebasing](https://docs.github.com/en/get-started/using-git/about-git-rebase) your commits and properly sign it. 
image

**Comment by iArchitSharma** [comment]
@Kingscliq we have two PR's on this, can we close this one?
If this PR does the same

**Comment by leecalcote** [comment]
@Kingscliq ?

**Pull request closed without merging**
