### PR TITLE
[UI] Updated the Github profiles section

### LINKED ISSUE #160: [UI] Update the Github profiles section
#### Current Behavior

image

#### Desired Behavior

image

#### Mockups

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**

### PR DESCRIPTION
**Pull request by akhilender-bongirwar**
**Description**

- Implemented UI updates to match the design in the Figma file, including layout improvements and color scheme adjustments.
- Added conditional rendering of the GitHub logo SVG for light and dark modes to enhance user experience.

This commit addresses the issue titled "[UI] Update the Github profiles section" by improving the visual appeal and smoothness of thewebsite according to the Figma design specifications. The updates ensure that the Github profiles section aligns seamlessly with the overall UI, providing a more polished and user-friendly interface.

This PR fixes #160 

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by gopivaibhav — COMMENTED** [review]
According to the [photo](https://layer5io.slack.com/archives/C015QJKUMPU/p1693564481418819?thread_ts=1693512033.664059&cid=C015QJKUMPU) you have shared on slack, I don't think GitHub logo is good looking with gray-ish background color. Maybe we need to use some dark color (probably black) around the octocat. @ritiksaxena124 Have you mentioned the same color to use for the circular background around it?

**Comment by akhilender-bongirwar** [comment]
> According to the [photo](https://layer5io.slack.com/archives/C015QJKUMPU/p1693564481418819?thread_ts=1693512033.664059&cid=C015QJKUMPU) you have shared on slack, I don't think GitHub logo is good looking with gray-ish background color. Maybe we need to use some dark color (probably black) around the octocat. @ritiksaxena124 Have you mentioned the same color to use for the circular background around it?

Hey @gopivaibhav  I have changed the color according to the color given by @ritiksaxena124 on slack channel. I have put exactly the same hex values as told by him. Yeah but still if you want me to change then please provide me with the hex value which you think is suitable.

**Comment by gopivaibhav** [comment]
Hi @akhilender-bongirwar Can you please share both dark and light mode screenshots of this section for easier comparison and review?
Thanks!!
@ritiksaxena124 Do you have any words to say here?

**Comment by akhilender-bongirwar** [comment]
**Screenshot for Dark Mode**
Screenshot 2023-09-03 121553


**Screen shot for Light Mode**
Screenshot 2023-09-03 121609


Here you go @gopivaibhav  : ) .....

**Comment by ritiksaxena124** [comment]
the colors look faded @akhilender-bongirwar in both dark and light mode

**Comment by akhilender-bongirwar** [comment]
> the colors look faded @akhilender-bongirwar in both dark and light mode

Hey @ritiksaxena124, I removed the opacity attribute and now the color looks vibrant. Please check : )

**Comment by ritiksaxena124** [comment]
Looks good @akhilender-bongirwar 👏. One last addition, Could you please pass the width and height prop to the SVG component

**Comment by akhilender-bongirwar** [comment]
Hi @ritiksaxena124 , I have made the required changes. Could you please review it ...  : )

**Comment by ritiksaxena124** [comment]
LGTM. thanks, @akhilender-bongirwar 👏🦾

**Comment by leecalcote** [comment]
Thanks, @akhilender-bongirwar 👍

**Pull request merged**
