### PR TITLE
Update meshery-cloud-release.yml

### LINKED ISSUE #408: [CI] Redefine Cloud Staging Deployment Script
### Current Behavior
See [this script](https://github.com/layer5labs/meshery-extensions-packages/blob/3d0c15bb5b5f4c082b3de15b5b2dac3734af41c8/.github/workflows/meshery-cloud-release.yml#L188-L208) as the current behavior.

### Desired Behavior
Support metal (equinix), not virtual deployments (aws)

### Implementation

Perhaps, https://github.com/marketplace/actions/deploy-to-kubernetes-cluster

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

### PR DESCRIPTION
**Pull request by sangramrath**
Update staging deployment to metal02 and remove ingress apply as a separate step in production (ingress has been fixed into values.yaml). METAL02_HOST, METAL02_USERNAME and METAL02_KEY may need to be created.

**Description**

This PR fixes #408

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Excellent! @sangramrath, to the extent that the key is consistent across each of the metal servers, I wonder if we might reuse the same secret.

**Comment by sangramrath** [comment]
@leecalcote I deliberately kept it separate to avoid confusion for anyone working on it later.

**Comment by leecalcote** [comment]
Words of wisdom, @sangramrath. Good call. https://github.com/layer5labs/meshery-extensions-packages/settings/secrets/actions should now be accessible. Please carry-on, if you would. 👍

**Review by leecalcote — APPROVED** [review]
LGTM

**Comment by leecalcote** [comment]
All three secrets have been added as org-level entries. We're good to go. 🚀

**Pull request merged**
