### PR TITLE
chore: decompose reusable workflow because it have some weird behavior

### PR DESCRIPTION
**Pull request by jerensl**
**Description**

Mixing between reusable workflow and dispatch comes with some unintended behavior for example missing input etc

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — APPROVED** [review]
I couldn’t find anything out of place here. This LGTM.

**Comment by leecalcote** [comment]
Does meshery/meshery need to be updated to dispatch the reusable workflow?

**Comment by leecalcote** [comment]
> Does meshery/meshery need to be updated to dispatch the reusable workflow?

>

**Comment by jerensl** [comment]
> Does meshery/meshery need to be updated to dispatch the reusable workflow?

No need, their only need to dispatch the dispatch workflow and the dispatcher will use the reusable workflow from here

**Pull request merged**
