### PR TITLE
Fix: leaderboard build errors

### PR DESCRIPTION
**Pull request by Kingscliq**
**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Kingscliq** [comment]
> **Description**
> 
> This PR fixes #
> 
> **Notes for Reviewers**
> 
> **[Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
> 
> * [ ]  Yes, I signed my commits.

This PR fixes the following:
  - build errors encountered during the deployment of the leaderboard
  - Inclusion of .babelrc file to accept jsx within components and objects
  - reafctor of the React query client for data fetching modifiied files includes gasby-ssr.js gatsby-browser.js and inclusion of a root file

**Comment by Kingscliq** [comment]
> > **Description**
> > This PR fixes #
> > **Notes for Reviewers**
> > **[Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
> > 
> > * [x]   Yes, I signed my commits.
> 
> This PR fixes the following:
> 
> * build errors encountered during the deployment of the leaderboard
> * Inclusion of .babelrc file to accept jsx within components and objects
> * reafctor of the React query client for data fetching modifiied files includes gasby-ssr.js gatsby-browser.js and inclusion of a root file

cc:  @leecalcote

**Comment by iArchitSharma** [comment]
No data found?
image

**Comment by Kingscliq** [comment]
> No data found? image

Hi @iArchitSharma Not sure why that is but we can get on a quick huddle on slack so I can verify, cause the api has always worked, secondly are u running the development build or the local build?

**Comment by Kingscliq** [comment]
Screenshot 2024-02-25 at 2 14 48 PM
I just checked as well and yeah the data was fetched successfully

**Comment by iArchitSharma** [comment]
@Kingscliq am actually using codespaces to run your pull, wasn't able to get it locally using github cli

**Comment by iArchitSharma** [comment]
image
image

**Comment by leecalcote** [comment]
@iArchitSharma any progress?

**Comment by iArchitSharma** [comment]
image (2)

**Review by iArchitSharma — APPROVED** [review]

**Pull request merged**
