### PR TITLE
[Cypress] Filters spec | CU-2p7c357

### PR DESCRIPTION
**Pull request by Chadha93**
Signed-off-by: Gaurav Chadha <gauravchadha1676@gmail.com>

**Description**
Filters spec

**Notes for Reviewers**
Currently, tests will fail for filters, because we don't drop and perform the actions on filters, written only the use-case tests.

**[Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by l5io** [comment]
Task linked: [CU-2p7c357 Open Applications and filter drawer and check for contents](https://app.clickup.com/t/2p7c357)

**Comment by Abhishek-kumar09** [comment]
Would you send a quick recording.

**Comment by Chadha93** [comment]
@Abhishek-kumar09

https://user-images.githubusercontent.com/65453826/186502241-8cb9faa9-8684-4dfe-b46b-9fcf9eef1a72.mp4

**Review by Abhishek-kumar09 — APPROVED** [review]
LGTM

**Pull request merged**
