### PR TITLE
[chore] move leaderboard to new location

### PR DESCRIPTION
**Pull request by leecalcote**
Signed-off-by: Lee Calcote <lee.calcote@layer5.io>

**Description**

This PR moves the board from /leaderboard to /discussion-leaderboard

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
@vishalvivekm an item that I asked you to ensure was completed...

**Comment by leecalcote** [comment]
@vishalvivekm this is awaiting your review.

**Comment by vishalvivekm** [comment]
> @vishalvivekm an item that I asked you to ensure was completed...

I intrepreted if you're asking to just comment the leaderboard link for now until it's made free of bugs that it has.

**Comment by vishalvivekm** [comment]
> @vishalvivekm this is awaiting your review.

Thank you. LGTM. @leecalcote

**Pull request merged**
